version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
    image: educon:v1.0.0
    container_name: educon_app
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
    networks:
      - laravel

networks:
  laravel:
